-- V1__create_notifications_table.sql (H2 Compatible)
-- Creates the notifications table with all required fields, constraints, and indexes
-- for the Notification System bounded context.

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    data CLOB,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    sent_at TIMESTAMP,
    delivered_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Domain Invariants: Constraints
    CONSTRAINT chk_title_not_empty CHECK (LENGTH(TRIM(title)) > 0),
    CONSTRAINT chk_message_not_empty CHECK (LENGTH(TRIM(message)) > 0),
    CONSTRAINT chk_type_valid CHECK (type IN ('PUSH', 'EMAIL', 'SMS'))
);

-- Indexes for efficient queries
-- Index on userId for retrieving user's notifications
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);

-- Index on sentAt for querying notifications by sent date (last 30 days queries)
CREATE INDEX IF NOT EXISTS idx_notifications_sent_at ON notifications(sent_at);

-- Composite index for unread notifications per user
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications(user_id, is_read);

-- Composite index for user recent notifications queries
CREATE INDEX IF NOT EXISTS idx_notifications_user_sent_at ON notifications(user_id, sent_at);

-- Composite index for user notifications ordered by created date
CREATE INDEX IF NOT EXISTS idx_notifications_user_created_at ON notifications(user_id, created_at);
