-- V1__create_service_tasks_table.sql (H2 Compatible)
-- Creates the service_tasks table with all required fields, constraints, and indexes
-- for the Task Management bounded context.

CREATE TABLE IF NOT EXISTS service_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description CLOB,
    client_address VARCHAR(500) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    estimated_duration INTEGER,
    status VARCHAR(20) NOT NULL DEFAULT 'UNASSIGNED',
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Domain Invariants: Constraints
    CONSTRAINT chk_title_not_empty CHECK (LENGTH(TRIM(title)) >= 3),
    CONSTRAINT chk_client_address_not_empty CHECK (LENGTH(TRIM(client_address)) > 0),
    CONSTRAINT chk_priority_valid CHECK (priority IN ('HIGH', 'MEDIUM', 'LOW')),
    CONSTRAINT chk_status_valid CHECK (status IN ('UNASSIGNED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT chk_estimated_duration_positive CHECK (estimated_duration IS NULL OR estimated_duration > 0)
);

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS idx_service_tasks_status ON service_tasks(status);
CREATE INDEX IF NOT EXISTS idx_service_tasks_priority ON service_tasks(priority);
CREATE INDEX IF NOT EXISTS idx_service_tasks_created_at ON service_tasks(created_at);
CREATE INDEX IF NOT EXISTS idx_service_tasks_created_by ON service_tasks(created_by);

-- Composite index for common queries
CREATE INDEX IF NOT EXISTS idx_service_tasks_status_priority ON service_tasks(status, priority);
