-- V2__create_assignments_table.sql (H2 Compatible)
-- Creates the assignments table with all required fields, constraints, and indexes
-- for the Assignment & Dispatch bounded context.

CREATE TABLE IF NOT EXISTS assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    technician_id BIGINT NOT NULL,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    reason VARCHAR(500),
    
    -- Domain Invariants: Constraints
    CONSTRAINT chk_assignment_status_valid CHECK (status IN ('ACTIVE', 'REASSIGNED', 'COMPLETED', 'CANCELLED')),
    
    -- Foreign key to service_tasks table
    CONSTRAINT fk_assignment_task FOREIGN KEY (task_id) REFERENCES service_tasks(id)
);

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS idx_assignments_task_id ON assignments(task_id);
CREATE INDEX IF NOT EXISTS idx_assignments_technician_id ON assignments(technician_id);
CREATE INDEX IF NOT EXISTS idx_assignments_status ON assignments(status);
CREATE INDEX IF NOT EXISTS idx_assignments_assigned_at ON assignments(assigned_at);

-- Composite index for technician workload queries
CREATE INDEX IF NOT EXISTS idx_assignments_technician_status ON assignments(technician_id, status);
