-- V4__create_assignment_history_table.sql (H2 Compatible)
-- Creates the assignment_history table for tracking all assignment changes (audit trail)
-- for the Assignment & Dispatch bounded context.

CREATE TABLE IF NOT EXISTS assignment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    technician_id BIGINT NOT NULL,
    previous_technician_id BIGINT,
    action VARCHAR(50) NOT NULL,
    action_by VARCHAR(255) NOT NULL,
    action_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason VARCHAR(500),
    
    -- Domain Invariants: Constraints
    CONSTRAINT chk_history_action_valid CHECK (action IN ('CREATED', 'REASSIGNED', 'COMPLETED', 'CANCELLED')),
    
    -- Foreign key to assignments table
    CONSTRAINT fk_history_assignment FOREIGN KEY (assignment_id) REFERENCES assignments(id)
);

-- Indexes for assignment_history
CREATE INDEX IF NOT EXISTS idx_history_assignment_id ON assignment_history(assignment_id);
CREATE INDEX IF NOT EXISTS idx_history_task_id ON assignment_history(task_id);
CREATE INDEX IF NOT EXISTS idx_history_technician_id ON assignment_history(technician_id);
CREATE INDEX IF NOT EXISTS idx_history_action_at ON assignment_history(action_at);
